name: test

on:
  push:
  pull_request:

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest
          #- macOS-latest
        nim_version:
          - '1.2.0'
          - 'stable'
    needs: before
    steps:
      - uses: actions/checkout@v1
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ matrix.nim_version }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: ${{ matrix.nim_version }}
      - name: Build examples
        run: |
          (cd examples/hello_world && nim c main.nim)
          (cd examples/calculator && nim c main.nim)
          (cd examples/novel && nim c main.nim)
          (cd examples/snake && nim c main.nim)
        shell: bash
      - name: Build tests
        run: |
          (cd tests && nim c test1.nim)
          (cd tests && nim c test2.nim)
          (cd tests && nim c test3.nim)
          (cd tests && nim c test4.nim)
          (cd tests && nim c test5.nim)
          (cd tests && nim c test6.nim)
          (cd tests && nim c test7.nim)
          (cd tests && nim c test8.nim)
          (cd tests && nim c test9.nim)
          (cd tests && nim c test10.nim)
          (cd tests && nim c test11.nim)
          (cd tests && nim c test12.nim)
          (cd tests && nim c test13.nim)
          (cd tests && nim c test14.nim)
          (cd tests && nim c test15.nim)
          (cd tests && nim c test16.nim)
          (cd tests && nim c test17.nim)
          (cd tests && nim c test18.nim)
          (cd tests && nim c test19.nim)
          (cd tests && nim c test20.nim)
          (cd tests && nim c test21.nim)
          (cd tests && nim c test22.nim)
          (cd tests && nim c test23.nim)
          (cd tests && nim c test24.nim)
        shell: bash
